### ISSUE TITLE
support for Gateway remote development

### ISSUE THREAD

**Issue by ArtsiomCh** [ArtsiomCh/CMake#33]
Created by request:
https://plugins.jetbrains.com/plugin/12869-cmake-plus/reviews#review=63269

**Comment by ArtsiomCh** [comment]
Just did try to connect to the host IDEA (with CMakePlus plugin) using **Gateway remote** through **Code With Me** link. And inside connected client functionality of CMakePlus plugin seems to be working fine...

**Comment by fty1777** [comment]
The host side CLion is launched automatically through Gateway and it is **headless**. I did not figure out how to configure and activate CMakePlus plugin on the host side since it's headless and auto-configured, with no X server and/or GUI support installed.

What I've done is just configuring the ssh connection to the server and let Gateway to finish all the stuff: installing IDE, launching it and establishing the connection. Then I can configure plugins and licenses in the client, and that's the only way to interact with the host IDE.  I am not able to open CLion GUI on the host and install the plugin and activate it directly without Gateway client. And the license is not correctly loaded in this case.

**Comment by ArtsiomCh** [comment]
@fty1777 I'm not able to setup ssh connection for Gateway :( So will try to do the fix according to my guesses.
Please install [CMake-plus-213.1.6-gateway-support-RC1.jar](https://drive.google.com/file/d/1DV8wT-W1O37yB2AZDi7x7SXEDsZuVR9F/view?usp=sharing) plugin version [from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk) and let me know if it works with your configuration.

**Comment by zskevind** [comment]
> @fty1777 I'm not able to setup ssh connection for Gateway :( So will try to do the fix according to my guesses. Please install [CMake-plus-213.1.6-gateway-support-RC1.jar](https://drive.google.com/file/d/1DV8wT-W1O37yB2AZDi7x7SXEDsZuVR9F/view?usp=sharing) plugin version [from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk) and let me know if it works with your configuration.

@ArtsiomCh It's working on my remote client, the "no license" warning disappeared,  Nice job!

**Comment by ArtsiomCh** [comment]
fixed in 213.1.7 version (should be available within few business days after JB approval)
PS folks, thanks for cooperating!
