### ISSUE TITLE
CMake Plus plugin have a probability of "License not found" in some cases

### ISSUE THREAD

**Issue by XiaoLey** [ArtsiomCh/CMake#37]
## Description
If I open or close any tab this time, or start or close any plugin, **CMake Plus** will have a chance to run normally the next time I start **CLion**. If I close all the tabs, no matter how many times I restart **CLion**, it works fine...

What's even weirder is that the problem only seems to be with my current project, however I open other projects with **CLion** and everything works fine.

I have a feeling that the problem seems to be related to the tabs I have open, but **CMake Plus** should not be affected by operations unrelated to it.

Could the problem have something to do with the filename of the files I'm opening, or CLion's syntax checking, or maybe the size of the project?

**CMake Plus Version:** 222.5.0

## Installed Plugs
- AceJump
- GrepConsole
- IdeaVIM
- IdeaVimExtension
- String Manipulation
- artsiomch.cmake
- artsiomch.cmake.plus
- com.dethlex.numberconverter
- com.intellij.plugins.vscodekeymap
- com.intellij.plugins.watcher
- com.jetbrains.plugins.ini4idea
- com.joshestein.ideavim-quickscope
- com.mallowigi
- com.markskelton.one-dark-theme
- com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete
- io.allandequeiroz.random.image.background
- izhangzhihao.rainbow.brackets
- mobi.hsz.idea.gitignore
- org.jetbrains.IdeaVim-EasyMotion
- ski.chrzanow.foldableprojectview
- some.awesome
- zielu.gittoolbox

## CLion 2022.2.3
Build #CL-222.4167.35, built on September 15, 2022
**Runtime version:** 17.0.4+7-b469.53 amd64
**VM:** OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by ArtsiomCh** [comment]
Thank you for detailed explanation and exploration of the issue!
Would you mind to give me the idea.log file to explore? [Locating IDE log files](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)

**Comment by XiaoLey** [comment]
Emailed you

**Comment by ArtsiomCh** [comment]
Got it, thanks!

**Comment by ArtsiomCh** [comment]
Looks like I found the root cause of the issue: it's IDE components race condition during startup.
Kind of regression of fixed [issue](https://github.com/ArtsiomCh/CMake/issues/29)
Please try this fixed version [222.5.1](https://drive.google.com/file/d/10sfoKCKZpcdfpOzw3AjdCvngtnjw859b/view?usp=sharing) and let me now please if the issue is actually fixed.

PS I saw the exceptions in the log from IdeaVim plugin and reported it [there](https://youtrack.jetbrains.com/issue/VIM-2768/SEVERE-ciouObjectTree-NotNull-method-comintellijopenapieditorClientEditorManagergetCurrentInstance-must-not-return-null).

**Comment by XiaoLey** [comment]
Now it's working fine.

**Comment by ArtsiomCh** [comment]
Great!
Thank you again for friendly cooperation!
